augmentation_level: light
backbone: efficientnet-b4
batch_size: 28
class_values:
- 41
- 76
- 90
- 124
- 161
- 0
data_path: /home/yyousfi1/commaai/comma10k
epochs: 30
eps: 1.0e-07
folder_to_predict: ../comma10k/
gpus: 2
height: 437
lr: 0.0001
num_workers: 6
resume_from_checkpoint: /home/yyousfi1/LogFiles/comma/efficientnet-b4/first-stage-pad-v2/checkpoints/last.ckpt
weight_decay: 0.001
width: 582
